import type { ChemicalElement, ChemicalElementType, KebabToSnakeCase } from '@/types';

export const TYPE: Record<Uppercase<KebabToSnakeCase<ChemicalElementType>>, ChemicalElementType> = {
  REACTIVE_NONMETAL: 'reactive-nonmetal',
  NOBLE_GASE: 'noble-gase',
  ALKALI_METAL: 'alkali-metal',
  ALKALI_EARTH_METAL: 'alkali-earth-metal',
  METALLOID: 'metalloid',
  POST_TRANSITION_METAL: 'post-transition-metal',
  TRANSITION_METAL: 'transition-metal',
  NOT_DEFINED: 'not-defined',
  LANTHANOID: 'lanthanoid',
  ACTINOID: 'actinoid',
} as const;

export const elements: ChemicalElement[] = [
  { atomicNumber: 1, chemicalSymbol: 'H', atomicMass: '1.008', group: 1, period: 1, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 2, chemicalSymbol: 'He', atomicMass: '4.0026', group: 18, period: 1, type: TYPE.NOBLE_GASE },

  { atomicNumber: 3, chemicalSymbol: 'Li', atomicMass: '6.94', group: 1, period: 2, type: TYPE.ALKALI_METAL },
  { atomicNumber: 4, chemicalSymbol: 'Be', atomicMass: '9.0122', group: 2, period: 2, type: TYPE.ALKALI_EARTH_METAL },
  { atomicNumber: 5, chemicalSymbol: 'B', atomicMass: '10.81', group: 13, period: 2, type: TYPE.METALLOID },
  { atomicNumber: 6, chemicalSymbol: 'C', atomicMass: '12.011', group: 14, period: 2, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 7, chemicalSymbol: 'N', atomicMass: '14.007', group: 15, period: 2, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 8, chemicalSymbol: 'O', atomicMass: '15.999', group: 16, period: 2, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 9, chemicalSymbol: 'F', atomicMass: '18.998', group: 17, period: 2, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 10, chemicalSymbol: 'Ne', atomicMass: '20.18', group: 18, period: 2, type: TYPE.NOBLE_GASE },

  { atomicNumber: 11, chemicalSymbol: 'Na', atomicMass: '22.99', group: 1, period: 3, type: TYPE.ALKALI_METAL },
  { atomicNumber: 12, chemicalSymbol: 'Mg', atomicMass: '24.305', group: 2, period: 3, type: TYPE.ALKALI_EARTH_METAL },
  {
    atomicNumber: 13,
    chemicalSymbol: 'Al',
    atomicMass: '26.982',
    group: 13,
    period: 3,
    type: TYPE.POST_TRANSITION_METAL,
  },
  { atomicNumber: 14, chemicalSymbol: 'Si', atomicMass: '28.085', group: 14, period: 3, type: TYPE.METALLOID },
  { atomicNumber: 15, chemicalSymbol: 'P', atomicMass: '30.974', group: 15, period: 3, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 16, chemicalSymbol: 'S', atomicMass: '32.06', group: 16, period: 3, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 17, chemicalSymbol: 'Cl', atomicMass: '35.45', group: 17, period: 3, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 18, chemicalSymbol: 'Ar', atomicMass: '39.948', group: 18, period: 3, type: TYPE.NOBLE_GASE },

  { atomicNumber: 19, chemicalSymbol: 'K', atomicMass: '39.098', group: 1, period: 4, type: TYPE.ALKALI_METAL },
  { atomicNumber: 20, chemicalSymbol: 'Ca', atomicMass: '40.078', group: 2, period: 4, type: TYPE.ALKALI_EARTH_METAL },
  { atomicNumber: 21, chemicalSymbol: 'Sc', atomicMass: '44.956', group: 3, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 22, chemicalSymbol: 'Ti', atomicMass: '47.867', group: 4, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 23, chemicalSymbol: 'V', atomicMass: '50.942', group: 5, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 24, chemicalSymbol: 'Cr', atomicMass: '51.996', group: 6, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 25, chemicalSymbol: 'Mn', atomicMass: '54.938', group: 7, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 26, chemicalSymbol: 'Fe', atomicMass: '55.845', group: 8, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 27, chemicalSymbol: 'Co', atomicMass: '58.933', group: 9, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 28, chemicalSymbol: 'Ni', atomicMass: '58.693', group: 10, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 29, chemicalSymbol: 'Cu', atomicMass: '63.546', group: 11, period: 4, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 30, chemicalSymbol: 'Zn', atomicMass: '65.38', group: 12, period: 4, type: TYPE.TRANSITION_METAL },
  {
    atomicNumber: 31,
    chemicalSymbol: 'Ga',
    atomicMass: '69.723',
    group: 13,
    period: 4,
    type: TYPE.POST_TRANSITION_METAL,
  },
  { atomicNumber: 32, chemicalSymbol: 'Ge', atomicMass: '72.630', group: 14, period: 4, type: TYPE.METALLOID },
  { atomicNumber: 33, chemicalSymbol: 'As', atomicMass: '74.922', group: 15, period: 4, type: TYPE.METALLOID },
  { atomicNumber: 34, chemicalSymbol: 'Se', atomicMass: '78.971', group: 16, period: 4, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 35, chemicalSymbol: 'Br', atomicMass: '79.904', group: 17, period: 4, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 36, chemicalSymbol: 'Kr', atomicMass: '83.798', group: 18, period: 4, type: TYPE.NOBLE_GASE },

  { atomicNumber: 37, chemicalSymbol: 'Rb', atomicMass: '85.468', group: 1, period: 5, type: TYPE.ALKALI_METAL },
  { atomicNumber: 38, chemicalSymbol: 'Sr', atomicMass: '87.620', group: 2, period: 5, type: TYPE.ALKALI_EARTH_METAL },
  { atomicNumber: 39, chemicalSymbol: 'Y', atomicMass: '88.906', group: 3, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 40, chemicalSymbol: 'Zr', atomicMass: '91.224', group: 4, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 41, chemicalSymbol: 'Nb', atomicMass: '92.906', group: 5, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 42, chemicalSymbol: 'Mo', atomicMass: '95.95', group: 6, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 43, chemicalSymbol: 'Tc', atomicMass: '(98)', group: 7, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 44, chemicalSymbol: 'Ru', atomicMass: '101.07', group: 8, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 45, chemicalSymbol: 'Rh', atomicMass: '102.91', group: 9, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 46, chemicalSymbol: 'Pd', atomicMass: '106.42', group: 10, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 47, chemicalSymbol: 'Ag', atomicMass: '107.87', group: 11, period: 5, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 48, chemicalSymbol: 'Cd', atomicMass: '112.41', group: 12, period: 5, type: TYPE.TRANSITION_METAL },
  {
    atomicNumber: 49,
    chemicalSymbol: 'In',
    atomicMass: '114.82',
    group: 13,
    period: 5,
    type: TYPE.POST_TRANSITION_METAL,
  },
  {
    atomicNumber: 50,
    chemicalSymbol: 'Sn',
    atomicMass: '118.71',
    group: 14,
    period: 5,
    type: TYPE.POST_TRANSITION_METAL,
  },
  { atomicNumber: 51, chemicalSymbol: 'Sb', atomicMass: '121.76', group: 15, period: 5, type: TYPE.METALLOID },
  { atomicNumber: 52, chemicalSymbol: 'Te', atomicMass: '127.600', group: 16, period: 5, type: TYPE.METALLOID },
  { atomicNumber: 53, chemicalSymbol: 'I', atomicMass: '126.90', group: 17, period: 5, type: TYPE.REACTIVE_NONMETAL },
  { atomicNumber: 54, chemicalSymbol: 'Xe', atomicMass: '131.29', group: 18, period: 5, type: TYPE.NOBLE_GASE },

  { atomicNumber: 55, chemicalSymbol: 'Cs', atomicMass: '132.91', group: 1, period: 6, type: TYPE.ALKALI_METAL },
  { atomicNumber: 56, chemicalSymbol: 'Ba', atomicMass: '137.33', group: 2, period: 6, type: TYPE.ALKALI_EARTH_METAL },
  { atomicNumber: 72, chemicalSymbol: 'Hf', atomicMass: '178.49', group: 4, period: 6, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 73, chemicalSymbol: 'Ta', atomicMass: '180.95', group: 5, period: 6, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 74, chemicalSymbol: 'W', atomicMass: '183.84', group: 6, period: 6, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 75, chemicalSymbol: 'Re', atomicMass: '186.21', group: 7, period: 6, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 76, chemicalSymbol: 'Os', atomicMass: '190.23', group: 8, period: 6, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 77, chemicalSymbol: 'Ir', atomicMass: '192.22', group: 9, period: 6, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 78, chemicalSymbol: 'Pt', atomicMass: '195.08', group: 10, period: 6, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 79, chemicalSymbol: 'Au', atomicMass: '196.97', group: 11, period: 6, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 80, chemicalSymbol: 'Hg', atomicMass: '200.59', group: 12, period: 6, type: TYPE.TRANSITION_METAL },
  {
    atomicNumber: 81,
    chemicalSymbol: 'Tl',
    atomicMass: '204.38',
    group: 13,
    period: 6,
    type: TYPE.POST_TRANSITION_METAL,
  },
  {
    atomicNumber: 82,
    chemicalSymbol: 'Pb',
    atomicMass: '207.2',
    group: 14,
    period: 6,
    type: TYPE.POST_TRANSITION_METAL,
  },
  {
    atomicNumber: 83,
    chemicalSymbol: 'Bi',
    atomicMass: '208.98',
    group: 15,
    period: 6,
    type: TYPE.POST_TRANSITION_METAL,
  },
  {
    atomicNumber: 84,
    chemicalSymbol: 'Po',
    atomicMass: '(209)',
    group: 16,
    period: 6,
    type: TYPE.POST_TRANSITION_METAL,
  },
  { atomicNumber: 85, chemicalSymbol: 'At', atomicMass: '(210)', group: 17, period: 6, type: TYPE.METALLOID },
  { atomicNumber: 86, chemicalSymbol: 'Rn', atomicMass: '(222)', group: 18, period: 6, type: TYPE.NOBLE_GASE },

  { atomicNumber: 87, chemicalSymbol: 'Fr', atomicMass: '(223)', group: 1, period: 7, type: TYPE.ALKALI_METAL },
  { atomicNumber: 88, chemicalSymbol: 'Ra', atomicMass: '(226)', group: 2, period: 7, type: TYPE.ALKALI_EARTH_METAL },
  { atomicNumber: 104, chemicalSymbol: 'Rf', atomicMass: '(226)', group: 4, period: 7, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 105, chemicalSymbol: 'Db', atomicMass: '(268)', group: 5, period: 7, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 106, chemicalSymbol: 'Sg', atomicMass: '(269)', group: 6, period: 7, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 107, chemicalSymbol: 'Bh', atomicMass: '(270)', group: 7, period: 7, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 108, chemicalSymbol: 'Hs', atomicMass: '(277)', group: 8, period: 7, type: TYPE.TRANSITION_METAL },
  { atomicNumber: 109, chemicalSymbol: 'Mt', atomicMass: '(278)', group: 9, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 110, chemicalSymbol: 'Ds', atomicMass: '(281)', group: 10, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 111, chemicalSymbol: 'Rg', atomicMass: '(282)', group: 11, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 112, chemicalSymbol: 'Cn', atomicMass: '(285)', group: 12, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 113, chemicalSymbol: 'Nh', atomicMass: '(286)', group: 13, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 114, chemicalSymbol: 'Fl', atomicMass: '(289)', group: 14, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 115, chemicalSymbol: 'Mc', atomicMass: '(290)', group: 15, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 116, chemicalSymbol: 'Lv', atomicMass: '(293)', group: 16, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 117, chemicalSymbol: 'Ts', atomicMass: '(294)', group: 17, period: 7, type: TYPE.NOT_DEFINED },
  { atomicNumber: 118, chemicalSymbol: 'Og', atomicMass: '(294)', group: 18, period: 7, type: TYPE.NOT_DEFINED },

  { atomicNumber: 57, chemicalSymbol: 'La', atomicMass: '138.91', group: 4, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 58, chemicalSymbol: 'Ce', atomicMass: '140.12', group: 5, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 59, chemicalSymbol: 'Pr', atomicMass: '140.91', group: 6, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 60, chemicalSymbol: 'Nd', atomicMass: '144.24', group: 7, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 61, chemicalSymbol: 'Pm', atomicMass: '(145)', group: 8, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 62, chemicalSymbol: 'Sm', atomicMass: '150.36', group: 9, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 63, chemicalSymbol: 'Eu', atomicMass: '151.96', group: 10, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 64, chemicalSymbol: 'Gd', atomicMass: '157.25', group: 11, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 65, chemicalSymbol: 'Tb', atomicMass: '158.93', group: 12, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 66, chemicalSymbol: 'Dy', atomicMass: '162.50', group: 13, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 67, chemicalSymbol: 'Ho', atomicMass: '164.93', group: 14, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 68, chemicalSymbol: 'Er', atomicMass: '167.26', group: 15, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 69, chemicalSymbol: 'Tm', atomicMass: '168.93', group: 16, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 70, chemicalSymbol: 'Yb', atomicMass: '173.05', group: 17, period: 6, type: TYPE.LANTHANOID },
  { atomicNumber: 71, chemicalSymbol: 'Lu', atomicMass: '174.97', group: 18, period: 6, type: TYPE.LANTHANOID },

  { atomicNumber: 89, chemicalSymbol: 'Ac', atomicMass: '(227)', group: 4, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 90, chemicalSymbol: 'Th', atomicMass: '232.04', group: 5, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 91, chemicalSymbol: 'Pa', atomicMass: '231.04', group: 6, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 92, chemicalSymbol: 'U', atomicMass: '238.03', group: 7, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 93, chemicalSymbol: 'Np', atomicMass: '(237)', group: 8, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 94, chemicalSymbol: 'Pu', atomicMass: '(244)', group: 9, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 95, chemicalSymbol: 'Am', atomicMass: '(243)', group: 10, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 96, chemicalSymbol: 'Cm', atomicMass: '(247)', group: 11, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 97, chemicalSymbol: 'Bk', atomicMass: '(247)', group: 12, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 98, chemicalSymbol: 'Cf', atomicMass: '(251)', group: 13, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 99, chemicalSymbol: 'Es', atomicMass: '(252)', group: 14, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 100, chemicalSymbol: 'Fm', atomicMass: '(257)', group: 15, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 101, chemicalSymbol: 'Md', atomicMass: '(258)', group: 16, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 102, chemicalSymbol: 'No', atomicMass: '(259)', group: 17, period: 7, type: TYPE.ACTINOID },
  { atomicNumber: 103, chemicalSymbol: 'Lr', atomicMass: '(266)', group: 18, period: 7, type: TYPE.ACTINOID },
];
